insert into authors (date_of_birth,name) values ('1998/11/18','Simon Tavara')
insert into authors (date_of_birth,name) values ('2000/02/10','Marcos Alcantara')
insert into authors (date_of_birth,name) values ('1999/01/11','Gustavo Ruiz')
insert into authors (date_of_birth,name) values ('2001/12/13','Giancarlo Yarleque')
insert into authors (date_of_birth,name) values ('2004/11/04','Efrain Holguin')
insert into authors (date_of_birth,name) values ('1996/10/08','Arnulfo Juarez')
insert into authors (date_of_birth,name) values ('1993/09/07','Arturo Benavente')
insert into authors (date_of_birth,name) values ('1995/03/01','Sofia Feliz')
insert into authors (date_of_birth,name) values ('1997/01/27','Cecilia Carcamo')
insert into authors (date_of_birth,name) values ('1991/04/31','Leslie Tandazo')
insert into authors (date_of_birth,name) values ('1964/03/24','Pedro Ibañez')


insert into books(author_id,is_bn) values(1,'NEW')
insert into books(author_id,is_bn) values(1,'OLD')
insert into books(author_id,is_bn) values(2,'NEW')
insert into books(author_id,is_bn) values(2,'OLD')
insert into books(author_id,is_bn) values(1,'USED')
insert into books(author_id,is_bn) values(3,'NEW')
insert into books(author_id,is_bn) values(3,'OLD')
insert into books(author_id,is_bn) values(2,'USED')
insert into books(author_id,is_bn) values(3,'USED')
insert into books(author_id,is_bn) values(4,'OLD')
insert into books(author_id,is_bn) values(5,'USED')
insert into books(author_id,is_bn) values(6,'USED')
insert into books(author_id,is_bn) values(7,'OLD')
insert into books(author_id,is_bn) values(8,'USED')
insert into books(author_id,is_bn) values(9,'USED')
insert into books(author_id,is_bn) values(10,'OLD')
insert into books(author_id,is_bn) values(11,'USED')
insert into books(author_id,is_bn) values(9,'USED')
insert into books(author_id,is_bn) values(10,'OLD')
insert into books(author_id,is_bn) values(8,'USED')
insert into books(author_id,is_bn) values(4,'USED')
insert into books(author_id,is_bn) values(5,'OLD')
insert into books(author_id,is_bn) values(7,'USED')
insert into books(author_id,is_bn) values(8,'USED')


insert into sale_items(book_id,customer_name,item_price) values(1,'VENDEDOR 1',192.95)
insert into sale_items(book_id,customer_name,item_price) values(2,'VENDEDOR 1',355.35)
insert into sale_items(book_id,customer_name,item_price) values(3,'VENDEDOR 2',963.65)
insert into sale_items(book_id,customer_name,item_price) values(3,'VENDEDOR 3',141.55)
insert into sale_items(book_id,customer_name,item_price) values(1,'VENDEDOR 2',92.45)
insert into sale_items(book_id,customer_name,item_price) values(2,'VENDEDOR 1',15.25)
insert into sale_items(book_id,customer_name,item_price) values(1,'VENDEDOR 3',852.45)
insert into sale_items(book_id,customer_name,item_price) values(4,'VENDEDOR 3',141.55)
insert into sale_items(book_id,customer_name,item_price) values(5,'VENDEDOR 2',92.45)
insert into sale_items(book_id,customer_name,item_price) values(6,'VENDEDOR 1',15.25)
insert into sale_items(book_id,customer_name,item_price) values(4,'VENDEDOR 3',852.45)
insert into sale_items(book_id,customer_name,item_price) values(5,'VENDEDOR 2',92.45)
insert into sale_items(book_id,customer_name,item_price) values(6,'VENDEDOR 1',15.25)
insert into sale_items(book_id,customer_name,item_price) values(7,'VENDEDOR 3',852.45)
insert into sale_items(book_id,customer_name,item_price) values(8,'VENDEDOR 2',92.45)
insert into sale_items(book_id,customer_name,item_price) values(9,'VENDEDOR 1',15.25)
insert into sale_items(book_id,customer_name,item_price) values(10,'VENDEDOR 3',852.45)
insert into sale_items(book_id,customer_name,item_price) values(11,'VENDEDOR 3',141.55)
insert into sale_items(book_id,customer_name,item_price) values(7,'VENDEDOR 2',92.45)
insert into sale_items(book_id,customer_name,item_price) values(5,'VENDEDOR 1',15.25)
insert into sale_items(book_id,customer_name,item_price) values(4,'VENDEDOR 3',852.45)
insert into sale_items(book_id,customer_name,item_price) values(5,'VENDEDOR 3',141.55)
insert into sale_items(book_id,customer_name,item_price) values(6,'VENDEDOR 2',92.45)
insert into sale_items(book_id,customer_name,item_price) values(9,'VENDEDOR 1',15.25)
insert into sale_items(book_id,customer_name,item_price) values(10,'VENDEDOR 3',852.45)